name: Scheduled Sync

on:
  schedule:
    - cron: '0 2 * * *'  # 每天UTC时间2点（北京时间10点）运行一次
  workflow_dispatch:

jobs:
  scheduled-sync:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: 安装 uv
        run: |
          pip install uv

      - name: 安装依赖
        run: |
          uv sync
     
      - name: 创建 .env 文件
        run: |
          echo "DIDA365_CLIENT_ID=${{ secrets.DIDA365_CLIENT_ID }}" >> .env
          echo "DIDA365_CLIENT_SECRET=${{ secrets.DIDA365_CLIENT_SECRET }}" >> .env
          echo "DIDA365_REDIRECT_URI=${{ secrets.DIDA365_REDIRECT_URI }}" >> .env
          echo "DIDA365_SERVICE_TYPE=${{ secrets.DIDA365_SERVICE_TYPE }}" >> .env
          echo "DIDA365_PROJECT_ID=${{ secrets.DIDA365_PROJECT_ID }}" >> .env
          echo "DIDA365_ACCESS_TOKEN=${{ secrets.DIDA365_ACCESS_TOKEN }}" >> .env
          echo "BUPT_ACCOUNT=${{ secrets.BUPT_ACCOUNT }}" >> .env
          echo "BUPT_PASSWORD=${{ secrets.BUPT_PASSWORD }}" >> .env
          echo "KETANGPAI_TOKEN=${{ secrets.KETANGPAI_TOKEN }}" >> .env
          echo "KETANGPAI_COURSE_ID=${{ secrets.KETANGPAI_COURSE_ID }}" >> .env

      - name: 运行同步服务
        run: |
          uv run main.py
